library:
  source-dirs: src
tests:
  haskell-fold-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - haskell-fold
    - hspec
    - matrix
copyright: 2019 Michael Rauh
maintainer: michaelrauh.github.io
dependencies:
- containers
- base >= 4.7 && < 5
- matrix
name: haskell-fold
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Michael Rauh
github: michaelrauh/haskell-fold
license: MIT
executables:
  haskell-fold-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-fold
description: Please see the README on GitHub at <https://github.com/michaelrauh/haskell-fold#readme>
